pages:
  image: node:14-alpine
  stage: deploy
  script:
    - npm ci --ignore-scripts --production --no-optional
    - yarn bootstrap
    - yarn build
    - cd packages/web-components
    - yarn export
    # Pull in instrument library
    - mkdir -p out/libraries/core/instruments
    - mv ../library-core/samples/* out/libraries/core/instruments
    # Pull in documentation
    - mv out ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
