pages:
  image: node:16-alpine
  stage: deploy
  script:
    - yarn install
    - yarn build
    - yarn export
    - mv packages/web/out ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
