image: node:20-alpine

test:
  stage: test
  script:
    - yarn install
    - yarn test

pages:
  stage: deploy
  variables:
    DAW_GOOGLE_ANALYTICS_ID: G-XC26HJXHKF
  script:
    - yarn install
    - yarn build
    - yarn doc
    - yarn export
    - mv packages/daw/out ./public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
