pages:
  image: node:14-alpine
  stage: deploy
  script:
    - yarn bootstrap
    - yarn build
    - yarn export
    - mv packages/web-components/out ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
