pages:
  image: node:14-alpine
  stage: deploy
  script:
    - npm ci --ignore-scripts --production --no-optional
    - npx lerna bootstrap --ignore-scripts -- --production --no-optional
    - cd packages/web
    - yarn export
    - mkdir -p out/libraries/core/instruments
    - mv ../library-core/samples/* out/libraries/core/instruments
    - mv out ../../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
